# Data Exploration

In this notebook describe your data exploration steps.

## Install dependencies

In [15]:
# %pip install -r requirements.txt

## Load data

In [16]:
import pandas as pd

df = pd.read_sql_table('cars', 'sqlite:///./cars.sqlite')

### Look at the first rows

In [17]:
df.head(10)

,date,CIN,name,petrol,diesel,gas,electro,hybrid,plugInHybrid,others
0,01.01.2022,01001,"Flensburg, kreisfreie Stadt",26809,16230,262,741,903,526,17
1,01.01.2022,01002,"Kiel, kreisfreie Stadt",71089,35234,713,1542,2324,1232,20
2,01.01.2022,01003,"Lübeck, kreisfreie Stadt",66824,30127,800,1171,2068,1168,9
3,01.01.2022,01004,"Neumünster, kreisfreie Stadt",26943,14163,317,694,857,453,8
4,01.01.2022,01051,"Dithmarschen, Landkreis",48386,32319,518,994,1092,433,21
5,01.01.2022,01053,"Herzogtum Lauenburg, Landkreis",75300,40192,1035,1574,1973,1088,19
6,01.01.2022,01054,"Nordfriesland, Landkreis",60707,41099,600,2119,1446,873,72
7,01.01.2022,01055,"Ostholstein, Landkreis",84081,41358,901,1503,1982,1083,20
8,01.01.2022,01056,"Pinneberg, Landkreis",118948,52023,1143,2568,4205,2023,37
9,01.01.2022,01057,"Plön, Landkreis",51167,27522,425,1150,1210,593,13